### ISSUE TITLE
Lack of integrity verification of downloaded external dependencies

### ISSUE THREAD

**Issue by mensfeld** [CloudCannon/pagebreak#1]
Hey,

My name is Maciej Mensfeld and I run a research security project called WhiteSource https://Diffend.io.

I've noticed, that this library downloads some external resources and uses them. While it's a totally common pattern, what is lacking here is integrity verification.

You could verify the integrity of the downloaded file before using it by comparing the file hash to a hardcoded, expected file hash.

This is essentially what package managers do to verify the integrity of downloaded packages.

Doing this would prevent attack scenarios in which `jekyll-pagebreak` is manipulated. I know the probability is low, but it always exists and on top of that, sometimes on some network issues, open-uri has a tendency to not raise error but end connection. This can lead to the package content being corrupted.

ref: https://my.diffend.io/gems/jekyll-pagebreak/0.1.1#d2h-127340-369

Have a great day :)

**Comment by bglw** [comment]
Thanks Maciej, good find. This is definitely the aim before a 1.0 release.
