### ISSUE TITLE
Build releases for more platforms

### ISSUE THREAD

**Issue by bglw** [CloudCannon/pagebreak#20]
Using the build targets of https://github.com/microsoft/ripgrep-prebuilt/ as a reference.

- [ ] aarch64-apple-darwin
- [ ] aarch64-pc-windows-msvc
- [ ] aarch64-unknown-linux-gnu
- [ ] arm-unknown-linux-gnueabihf
- [ ] i686-pc-windows-msvc
- [ ] i686-unknown-linux-musl
- [ ] powerpc64le-unknown-linux-gnu
- [ ] s390x-unknown-linux-gnu
- [x] x86_64-apple-darwin
- [x] x86_64-pc-windows-msvc
- [x] x86_64-unknown-linux-musl

**Comment by MoElaSec** [comment]
no M1 support yet

**Comment by bglw** [comment]
👋 Hi @MoElaSec, can you paste the error you encountered with the platform string that is missing? As far as I'm aware, in #30 we released Pagebreak 0.9.0 which runs on M1. 

In terms of native support, we'll need Actions to add an M1 runner so we can run our release action (https://github.com/actions/virtual-environments/issues/2187)

If you're encountering an unsupported platform string, we should be able to alias it to the `x86_64-apple-darwin` binary which AFAIK runs fine on M1 via Rosetta.

**Comment by BitnooriLee** [comment]
Unsupported platform: arm64-darwin21

I got this error.

**Comment by bglw** [comment]
Hi @BitnooriLee — thanks for that. I'll revisit the platform matching

**Comment by ozgunozerk** [comment]
That's wonderful news! Any idea on when will it be released?

**Comment by bglw** [comment]
The build containing M1 support went out November 24 so it should be working now — are you seeing issues?

**Comment by bglw** [comment]
Oh my, sorry I've just realized I'm in the wrong repo 🤦 I thought this was Pagefind, not Pagebreak.

Apologies! M1 release isn't published yet, but it will be soon! (As I can move the CI configuration over from Pagefind)

**Comment by ozgunozerk** [comment]
I want to use Vonge Jekyll theme, however it uses `pagebreak` and that is not building as a dependency for M1. 
Any idea on when will this be fixed, or any easy workaround you have on your mind for making Vonge work for M1?
Thanks in advance, appreciate the open-source work here 👍

**Comment by ozgunozerk** [comment]
any updates?

**Comment by ozgunozerk** [comment]
Is this abandoned?

**Comment by bglw** [comment]
Hey @ozgunozerk, sorry for the lack of updates here. Definitely not abandoned! I’ll block out some time on my calendar this coming week to bring the publishing of this repository up to spec.

**Comment by bglw** [comment]
Hi @ozgunozerk and others 👋 

I've updated Pagebreak to match the rest of our open source suite, which distributes standalone binaries with an npx wrapper.

The latest Pagebreak release changes to this distribution method, and in doing so expands the platform support to match that of our other packages. 

This does mean you'll have to slightly tweak your setup to use the new Pagebreak version. See the new [Usage documentation here](https://github.com/CloudCannon/pagebreak/#usage) for details.

Let me know if you have any issues with the new installation.

**Comment by ozgunozerk** [comment]
Thanks a lot! I couldn't manage to install it for `vonge`. 
Seems like `vonge` still uses version 0.6.0 for the pagebreak. I tried to yank the version in the gem files, but was not successful. 

The error I'm getting is: 
<img width="1564" alt="image" src="https://user-images.githubusercontent.com/32795992/225563180-cb493183-506c-46ed-adee-dbbe1ba19b06.png">

I'm a novice in Jekyll and ruby, do you have any suggestions on what should I do?

**Comment by bglw** [comment]
The new release is distributed as a standalone command rather than a plugin, so you'll need to remove `jekyll-pagebreak` from the `Gemfile` and `_config.yml`.

Instead now, after building your site you need to run the pagebreak command to post-process the files.

Here's the PR making the changes required to the Vonge template repo: https://github.com/CloudCannon/vonge-jekyll-bookshop-template/pull/21

Since this template is targeting CloudCannon's environment, the command has been added in a `postbuild` script.

For running locally or on another hosting platform, you'll just want to run 
```bash
bundle exec jekyll build && npx -y @pagebreak/cli --source _site --output _site
```

_(This does have the unfortunate downside that when running `jekyll serve` locally you won't see the pagination in action, but it has no different for your production build)_

**Comment by ozgunozerk** [comment]
Thanks, the PR link was quite helpful! 🙌
