### ISSUE TITLE
Support Ruby 3.0

### ISSUE THREAD

**Issue by bglw** [CloudCannon/pagebreak#32]
See [vonge-jekyll-bookshop-template#4](https://github.com/CloudCannon/vonge-jekyll-bookshop-template/issues/4)

**Comment by dm807cam** [comment]
Any updates on this?

**Comment by bglw** [comment]
Thanks for the bump @dm807cam — If you upgrade to `jekyll-pagebreak` 0.9.1 this should now be working on Ruby >= 3.
